version: '3'
services:
  db: 
   image: postgres
   container_name: lab1-db
   env_file: .env
  web:
    build: .
    container_name: lab1-web
    env_file: .env
    command: sh /webapp/scripts/startup.sh
    ports:
     - "80:3000"
    volumes:
     - .:/webapp
    links:
      - db